name: NPM Build and Push Docker Image

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
  pull_request_target:
    branches:
      - 'development'
      - 'rc/**'
      - 'hotfix/**'
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: gzac-frontend
  GITHUB_NAMESPACE: generiekzaakafhandelcomponent

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagToDeploy: ${{ steps.prep.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: 'Generate unique docker tag to deploy'
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +'%Y%m%d%H%M')
          echo "image_tag=${branch}-${ts}-${sha}" >> "$GITHUB_OUTPUT"

      - name: NPM install and build
        run: |
          npm install
          npm run build

      - name: Preparation step
        run: mkdir build | mv deployment/ conf/ build/

      - name: Archive dist folder
        uses: actions/upload-artifact@v2
        with:
          name: gzac-frontend-dist
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: gzac-frontend-dist

      - name: 'Login to github packages'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.tagToDeploy }}
